//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialRegistration.NFCRingRPC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NFCRingRPC.IRPC")]
    public interface IRPC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRPC/CredProtect", ReplyAction="http://tempuri.org/IRPC/CredProtectResponse")]
        string CredProtect(string pzw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRPC/CredProtect", ReplyAction="http://tempuri.org/IRPC/CredProtectResponse")]
        System.Threading.Tasks.Task<string> CredProtectAsync(string pzw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRPCChannel : CredentialRegistration.NFCRingRPC.IRPC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RPCClient : System.ServiceModel.ClientBase<CredentialRegistration.NFCRingRPC.IRPC>, CredentialRegistration.NFCRingRPC.IRPC {
        
        public RPCClient() {
        }
        
        public RPCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RPCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CredProtect(string pzw) {
            return base.Channel.CredProtect(pzw);
        }
        
        public System.Threading.Tasks.Task<string> CredProtectAsync(string pzw) {
            return base.Channel.CredProtectAsync(pzw);
        }
    }
}
