//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

DEFINE_GUID(CLSID_CredGrabber, 0x8eb4e5f7, 0x9dfb, 0x4674, 0x89, 0x7c, 0x2a, 0x58, 0x49, 0x34, 0xcd, 0xbf);


